_name_or_path:
    value: /root/autodl-tmp/models/Qwen3-0.6B-Base
_wandb:
    value:
        cli_version: 0.24.2
        e:
            uyow4gmhtk1rief0fgasyfswzz4wkexj:
                codePath: sft_qwen.py
                codePathLocal: sft_qwen.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "18964480000"
                email: yxf827206205@163.com
                executable: /root/miniconda3/bin/python
                gpu: NVIDIA GeForce RTX 4090 D
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 14592
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090 D
                      uuid: GPU-f9dfaf6e-69fc-ee80-f429-a430d31ab473
                host: autodl-container-pkzaz5b57z-90d5c4f3
                memory:
                    total: "540638674944"
                os: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
                program: /root/autodl-tmp/qwen/sft_qwen.py
                python: CPython 3.12.3
                root: /root/autodl-tmp/qwen
                startedAt: "2026-02-23T01:34:54.886483Z"
                writerId: uyow4gmhtk1rief0fgasyfswzz4wkexj
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 98
                - 105
            "3":
                - 2
                - 7
                - 13
                - 19
                - 62
                - 66
            "4": 3.12.3
            "5": 0.24.2
            "6": 4.57.1
            "9":
                "1": transformers_trainer
            "12": 0.24.2
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
activation_offloading:
    value: false
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - Qwen3ForCausalLM
assistant_only_loss:
    value: false
attention_bias:
    value: false
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: true
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: true
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chat_template_path:
    value: null
chunk_size_feed_forward:
    value: 0
completion_only_loss:
    value: null
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 4
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
dataset_kwargs:
    value: null
dataset_num_proc:
    value: null
dataset_text_field:
    value: text
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: false
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
dtype:
    value: bfloat16
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token:
    value: <EOS_TOKEN>
eos_token_id:
    value: 151643
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_packing:
    value: null
eval_steps:
    value: null
eval_strategy:
    value: "no"
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 2
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value:
        use_reentrant: false
greater_is_better:
    value: null
group_by_length:
    value: false
half_precision_backend:
    value: auto
head_dim:
    value: 128
hidden_act:
    value: silu
hidden_size:
    value: 1024
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: "no"
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 3072
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_types:
    value:
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
        - full_attention
learning_rate:
    value: 0.0001
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: /root/autodl-tmp/checkpoints/qwen_sft_use_tool/runs/Feb23_09-35-02_autodl-container-pkzaz5b57z-90d5c4f3
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
loss_type:
    value: nll
lr_scheduler_kwargs:
    value: null
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 1
max_length:
    value: 1024
max_position_embeddings:
    value: 32768
max_steps:
    value: -1
max_window_layers:
    value: 28
metric_for_best_model:
    value: null
min_length:
    value: 0
model/num_parameters:
    value: 926592000
model_init_kwargs:
    value: null
model_type:
    value: qwen3
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 16
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 28
num_key_value_heads:
    value: 8
num_return_sequences:
    value: 1
num_train_epochs:
    value: 1
optim:
    value: adamw_torch_fused
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: /root/autodl-tmp/checkpoints/qwen_sft_use_tool
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
packing:
    value: true
packing_strategy:
    value: bfd
pad_to_multiple_of:
    value: null
pad_token:
    value: <PAD_TOKEN>
pad_token_id:
    value: 151643
padding_free:
    value: false
parallelism_config:
    value: null
past_index:
    value: -1
peft_config:
    value:
        default:
            alora_invocation_tokens: null
            arrow_config: null
            auto_mapping: null
            base_model_name_or_path: /root/autodl-tmp/models/Qwen3-0.6B-Base
            bias: none
            corda_config: null
            ensure_weight_tying: false
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 64
            lora_bias: false
            lora_dropout: 0.05
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save:
                - embed_tokens
                - lm_head
            peft_type: LORA
            peft_version: 0.18.1
            qalora_group_size: 16
            r: 32
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - gate_proj
                - o_proj
                - up_proj
                - k_proj
                - q_proj
                - down_proj
                - v_proj
            target_parameters: null
            task_type: CAUSAL_LM
            trainable_token_indices: null
            use_dora: false
            use_qalora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 6
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
project:
    value: huggingface
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: false
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rms_norm_eps:
    value: 1e-06
rope_scaling:
    value: null
rope_theta:
    value: 1000000
run_name:
    value: qwen-use-tool-sft
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 200
save_strategy:
    value: steps
save_total_limit:
    value: null
seed:
    value: 42
sep_token_id:
    value: null
shuffle_dataset:
    value: false
skip_memory_metrics:
    value: true
sliding_window:
    value: null
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
trackio_space_id:
    value: trackio
transformers_version:
    value: 4.57.1
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_cpu:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
use_sliding_window:
    value: false
vocab_size:
    value: 151673
warmup_ratio:
    value: 0.05
warmup_steps:
    value: 0
weight_decay:
    value: 0
